spring.application.name=authify

spring.datasource.url=jdbc:mysql://localhost:3306/authify_app
spring.datasource.username=root
spring.datasource.password=sadguru@123@123
spring.jpa.hibernate.ddl-auto=update


jwt.secret.key=thisisthesecretkeyievercreatedinmydevelopmentcarrer

server.servlet.context-path=/api/v1.0